{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  labels:
    app: jenkins
type: Opaque
data:
  jenkins-admin-username: {{ .Values.adminUsername | b64enc | quote }}
  jenkins-admin-password: {{ .Values.adminPassword | b64enc | quote }}
{{- end }}
